
import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/providers/ThemeProvider";
import {AuthProvider} from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body
      >
      <AuthProvider>
          <ThemeProvider>
              <div className={"flex h-[100vh] justify-center items-center w-full"}>
                  {children}
              </div>
          </ThemeProvider>
      </AuthProvider>
      </body>
      </html>
  );
}
